print ("Como te llamas?")
name=input()
print("Hola," + " " + name + "!")
print("Encantado de conocerte")
print("Que tal te va el día" + "?")
que=input()
print ("Y eso" + "" + "?")
input()
print ("vaya")