print ("Como te llamas?")
name= input()
print ("Esta bien, buenas" " " + (name))
print ("Aquí intentarás hacer tu propia historia de un gran heroe")
print ("Empecemos, como se llama tu heroe?")
heroe=input()
print ("Con que" + " " + heroe + " " + "me parece un gran nombre")
print ("Ahora, quien será tu gran enemigo?")
enemigo= input()
print ("No esta mal novato")
print ("Que piensas hacer para ganarle?")
combate=input()
print ("Que conseguiras con esto?")
tesoro= input()
print ("Donde se desarroyara tu historia?")
lugar= input()
print ("Que ha hecho tu enemigo?")
causa= input()


print  ("Esta bien, creemos tu historia:")
print ("Cuenta la leyenda que un lejano lugar llamado" + " " + lugar + " " + "todos sus habitantes vivieron felizes hasta que" + " " + enemigo + " " + "ataco")
